name: SBOM Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  falco-runtime:
    name: Falco Runtime Capture
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Falco
        uses: falcosecurity/falco-actions/start@main
        with:
          mode: analyze
          verbose: true

      - name: Trigger suspicious activity
        run: |
          docker rm -f nginx-test || true
          docker run -d --name nginx-test nginx:1.14
          docker exec nginx-test sh -c "
            wget https://example.com || true;
            cat /etc/shadow || true;
          "

      - name: Stop Falco
        if: always()
        uses: falcosecurity/falco-actions/stop@main
        with:
          mode: analyze
          verbose: true

  falco-analyze:
    name: Falco Analyze Report
    runs-on: ubuntu-latest
    needs: falco-runtime

    permissions:
      contents: read
      actions: read

    steps:
      - name: Analyze Falco events
        uses: falcosecurity/falco-actions/analyze@main
        with:
          falco-version: '0.39.0'